# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcB8g1As-Vi4U_ZXzAJ1uVZtwM2ia3RU
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------
st.set_page_config(
    page_title="Outlier Detection App",
    page_icon="📊",
    layout="wide"
)

# ---------------------------------------------------
# HEADER
# ---------------------------------------------------
st.markdown(
    """
    <h1 style='text-align:center;color:#4CAF50;'>
    📊 Outlier Detection using IQR Method
    </h1>
    <h4 style='text-align:center;color:gray;'>
    Upload your dataset and detect/remove outliers instantly
    </h4>
    """,
    unsafe_allow_html=True,
)

st.divider()

# ---------------------------------------------------
# FILE UPLOAD
# ---------------------------------------------------
uploaded_file = st.file_uploader(
    "Upload CSV File",
    type=["csv"]
)

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.success("Dataset Loaded Successfully")

    st.subheader("Dataset Preview")

    st.dataframe(df.head())

    # ---------------------------------------------------
    # STATISTICS
    # ---------------------------------------------------

    st.subheader("Dataset Statistics")

    st.dataframe(df.describe())

    numeric_cols = df.select_dtypes(include=np.number).columns

    if len(numeric_cols) == 0:
        st.error("No Numeric Columns Found")
        st.stop()

    column = st.selectbox(
        "Select Numeric Column",
        numeric_cols
    )

    # ---------------------------------------------------
    # BOXPLOT
    # ---------------------------------------------------

    st.subheader("Box Plot")

    fig, ax = plt.subplots(figsize=(8,4))

    ax.boxplot(df[column])

    ax.set_ylabel(column)

    st.pyplot(fig)

    # ---------------------------------------------------
    # HISTOGRAM
    # ---------------------------------------------------

    st.subheader("Histogram")

    fig2, ax2 = plt.subplots(figsize=(8,4))

    ax2.hist(df[column], bins=30)

    ax2.set_xlabel(column)

    ax2.set_ylabel("Frequency")

    st.pyplot(fig2)

    # ---------------------------------------------------
    # IQR METHOD
    # ---------------------------------------------------

    Q1 = df[column].quantile(0.25)

    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR

    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

    clean_df = df[
        (df[column] >= lower) &
        (df[column] <= upper)
    ]

    # ---------------------------------------------------
    # RESULTS
    # ---------------------------------------------------

    st.subheader("IQR Calculation")

    c1, c2, c3, c4, c5 = st.columns(5)

    c1.metric("Q1", round(Q1,2))
    c2.metric("Q3", round(Q3,2))
    c3.metric("IQR", round(IQR,2))
    c4.metric("Lower Bound", round(lower,2))
    c5.metric("Upper Bound", round(upper,2))

    st.subheader("Outlier Summary")

    a, b, c = st.columns(3)

    a.metric("Original Rows", len(df))

    b.metric("Outliers", len(outliers))

    c.metric("Clean Rows", len(clean_df))

    # ---------------------------------------------------
    # OUTLIERS
    # ---------------------------------------------------

    st.subheader("Detected Outliers")

    st.dataframe(outliers)

    # ---------------------------------------------------
    # CLEAN DATASET
    # ---------------------------------------------------

    st.subheader("Dataset after Removing Outliers")

    st.dataframe(clean_df)

    csv = clean_df.to_csv(index=False).encode("utf-8")

    st.download_button(
        "⬇ Download Clean Dataset",
        csv,
        file_name="clean_dataset.csv",
        mime="text/csv"
    )

else:
    st.info("Please upload a CSV file to begin.")

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------

st.divider()

st.markdown(
    """
    <div style='text-align:center;color:gray'>
    Developed with ❤️ by <b>Akanksha Mishra</b><br>
    Streamlit • Pandas • NumPy • Matplotlib
    </div>
    """,
    unsafe_allow_html=True,
)