# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qDX3itwIDgdmBNosxfXrGzHV07N1aEw
"""

!pip install streamlit
!pip install joblib

import streamlit as st
import numpy as np
from PIL import Image
import joblib

# -------------------------
# Page Configuration
# -------------------------
st.set_page_config(
    page_title="Male vs Female Classifier",
    page_icon="👤",
    layout="centered"
)

# -------------------------
# Load Model
# -------------------------
model = joblib.load("male_female_model.pkl")

IMG_SIZE = 64

# -------------------------
# Title
# -------------------------
st.title("👨👩 Male vs Female Image Classifier")
st.write("Upload a face image to predict whether it is Male or Female.")

# -------------------------
# Upload Image
# -------------------------
uploaded_file = st.file_uploader(
    "Choose an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    # Read image
    image = Image.open(uploaded_file)

    # Convert image to RGB
    image = image.convert("RGB")

    # Display uploaded image
    st.image(image, caption="Uploaded Image", width=300)

    # Resize image
    resized = image.resize((IMG_SIZE, IMG_SIZE))

    # Convert image to NumPy array
    resized = np.array(resized)

    # Flatten image
    resized = resized.flatten()

    # Prediction
    prediction = model.predict([resized])[0]

    # Prediction probabilities
    probability = model.predict_proba([resized])[0]

    # Display result
    if prediction == 0:
        st.success("👩 Prediction: FEMALE")
    else:
        st.success("👨 Prediction: MALE")

    # Display confidence
    st.subheader("Prediction Confidence")

    st.write(f"👩 Female Probability: **{probability[0] * 100:.2f}%**")
    st.write(f"👨 Male Probability: **{probability[1] * 100:.2f}%**")

import os
import cv2
import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression

# -------------------------
# Dataset Path
# -------------------------
dataset_path = r"/content/sample_data/DATASET"

images = []
labels = []

# Class Names
classes = ["FEMALE", "MALE"]      # 0 = Female, 1 = Male

IMG_SIZE = 64

# -------------------------
# Load Images
# -------------------------
for label, folder in enumerate(classes):

    folder_path = os.path.join(dataset_path, folder)

    for file in os.listdir(folder_path):

        img_path = os.path.join(folder_path, file)

        img = cv2.imread(img_path)

        if img is None:
            continue

        # Resize image
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        # Flatten image
        img = img.flatten()

        images.append(img)
        labels.append(label)

# -------------------------
# Prepare Dataset
# -------------------------
X = np.array(images)
y = np.array(labels)

print("Training Images:", len(X))
print("Image Shape:", X.shape)
print("Labels Shape:", y.shape)

# -------------------------
# Train Logistic Regression
# -------------------------
model = LogisticRegression(max_iter=1000)

model.fit(X, y)

# -------------------------
# Save Model
# -------------------------
joblib.dump(model, "male_female_model.pkl")

print("Model Saved Successfully!")