# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyS0VP7ZzcLrhIf-6turPABKfi_r_wGf
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# ---------------- PAGE CONFIG ---------------- #
st.set_page_config(
    page_title="Google Play Store Analytics Dashboard",
    page_icon="📱",
    layout="wide"
)

# ---------------- CUSTOM CSS ---------------- #
st.markdown("""
<style>
.main{
    background-color:#f8f9fa;
}
div[data-testid="metric-container"]{
    background:white;
    padding:15px;
    border-radius:10px;
    box-shadow:0px 2px 8px rgba(0,0,0,0.15);
}
h1,h2,h3{
    color:#0F62FE;
}
</style>
""", unsafe_allow_html=True)

# ---------------- LOAD DATA ---------------- #
@st.cache_data
def load_data():

    df = pd.read_csv("googleplaystore_v2.csv")

    # Remove missing ratings
    df = df.dropna(subset=["Rating"])

    # Numeric columns
    df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")
    df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

    # Clean Installs
    df["Installs"] = (
        df["Installs"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("+", "", regex=False)
    )
    df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

    # Clean Price
    df["Price"] = (
        df["Price"]
        .astype(str)
        .str.replace("$", "", regex=False)
    )
    df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

    # Clean Size
    def clean_size(x):

        if pd.isna(x):
            return np.nan

        x = str(x)

        if x == "Varies with device":
            return np.nan

        if x.endswith("M"):
            return float(x[:-1])

        if x.endswith("k"):
            return float(x[:-1]) / 1024

        return np.nan

    df["Size"] = df["Size"].apply(clean_size)

    return df


# Load Data
df = load_data()

# ---------------- SIDEBAR ---------------- #
st.sidebar.header("Filters")

category = st.sidebar.multiselect(
    "Category",
    sorted(df["Category"].dropna().unique()),
    default=sorted(df["Category"].dropna().unique())
)

app_type = st.sidebar.multiselect(
    "Type",
    sorted(df["Type"].dropna().unique()),
    default=sorted(df["Type"].dropna().unique())
)

content = st.sidebar.multiselect(
    "Content Rating",
    sorted(df["Content Rating"].dropna().unique()),
    default=sorted(df["Content Rating"].dropna().unique())
)

filtered = df[
    (df["Category"].isin(category)) &
    (df["Type"].isin(app_type)) &
    (df["Content Rating"].isin(content))
]

# ---------------- TITLE ---------------- #
st.title("📱 Google Play Store Analytics Dashboard")
st.write("Analyze app performance using ratings, installs, reviews, price and size.")

# ---------------- KPI CARDS ---------------- #
total_apps = len(filtered)
avg_rating = filtered["Rating"].mean()
avg_reviews = int(filtered["Reviews"].fillna(0).mean())
total_installs = int(filtered["Installs"].fillna(0).sum())

c1, c2, c3, c4 = st.columns(4)

c1.metric("📱 Total Apps", f"{total_apps:,}")
c2.metric("⭐ Avg Rating", f"{avg_rating:.2f}")
c3.metric("📝 Avg Reviews", f"{avg_reviews:,}")
c4.metric("⬇️ Total Installs", f"{total_installs:,}")

st.markdown("---")

# ---------------- RATING DISTRIBUTION ---------------- #
col1, col2 = st.columns(2)

with col1:
    fig = px.histogram(
        filtered,
        x="Rating",
        nbins=20,
        color_discrete_sequence=["royalblue"],
        title="Rating Distribution"
    )
    st.plotly_chart(fig, use_container_width=True)

# ---------------- TOP CATEGORIES ---------------- #
with col2:
    category_rating = (
        filtered.groupby("Category")["Rating"]
        .mean()
        .sort_values(ascending=False)
        .head(10)
        .reset_index()
    )

    fig = px.bar(
        category_rating,
        x="Rating",
        y="Category",
        orientation="h",
        color="Rating",
        title="Top 10 Categories by Rating"
    )
    st.plotly_chart(fig, use_container_width=True)

st.markdown("---")

# ---------------- SCATTER PLOTS ---------------- #
col3, col4 = st.columns(2)

with col3:
    fig = px.scatter(
        filtered,
        x="Reviews",
        y="Rating",
        color="Type",
        hover_name="App",
        title="Reviews vs Rating"
    )
    st.plotly_chart(fig, use_container_width=True)

with col4:
    fig = px.scatter(
        filtered,
        x="Installs",
        y="Rating",
        color="Category",
        hover_name="App",
        title="Installs vs Rating"
    )
    st.plotly_chart(fig, use_container_width=True)

st.markdown("---")

# ---------------- SIZE & PRICE ---------------- #
col5, col6 = st.columns(2)

with col5:
    fig = px.scatter(
        filtered,
        x="Size",
        y="Rating",
        color="Category",
        hover_name="App",
        title="Size vs Rating"
    )
    st.plotly_chart(fig, use_container_width=True)

with col6:
    fig = px.scatter(
        filtered,
        x="Price",
        y="Rating",
        color="Type",
        hover_name="App",
        title="Price vs Rating"
    )
    st.plotly_chart(fig, use_container_width=True)

st.markdown("---")
# ---------------- FREE VS PAID ---------------- #
col7, col8 = st.columns(2)

with col7:
    fig = px.box(
        filtered,
        x="Type",
        y="Rating",
        color="Type",
        title="Free vs Paid Ratings"
    )
    st.plotly_chart(fig, use_container_width=True)

with col8:
    corr = filtered[
        ["Rating", "Reviews", "Installs", "Price", "Size"]
    ].corr()

    fig = px.imshow(
        corr,
        text_auto=".2f",
        color_continuous_scale="Viridis",
        title="Correlation Heatmap"
    )
    st.plotly_chart(fig, use_container_width=True)

st.markdown("---")

# ---------------- TOP APPS ---------------- #
st.subheader("🏆 Top 10 Highest Rated Apps")

top_apps = (
    filtered.sort_values(
        ["Rating", "Reviews"],
        ascending=False
    )[["App", "Category", "Rating", "Reviews", "Installs"]]
    .head(10)
)

st.dataframe(top_apps, use_container_width=True)

st.markdown("---")

# ---------------- DATA EXPLORER ---------------- #
st.subheader("📄 Data Explorer")

st.dataframe(
    filtered,
    use_container_width=True,
    height=350
)

csv = filtered.to_csv(index=False).encode("utf-8")

st.download_button(
    "⬇ Download Filtered Dataset",
    data=csv,
    file_name="filtered_googleplaystore.csv",
    mime="text/csv"
)

st.markdown("---")

# ---------------- INSIGHTS ---------------- #
st.subheader("💡 Insights")

if not filtered.empty:

    highest_category = (
        filtered.groupby("Category")["Rating"]
        .mean()
        .idxmax()
    )

    highest_install = (
        filtered.groupby("Category")["Installs"]
        .sum()
        .idxmax()
    )

    st.success(
        f"⭐ Highest Rated Category: {highest_category}"
    )

    st.info(
        f"📥 Most Installed Category: {highest_install}"
    )

    install_corr = filtered["Rating"].corr(filtered["Installs"])
    review_corr = filtered["Rating"].corr(filtered["Reviews"])

    if install_corr > 0.5:
        st.write("✅ Apps with more installs generally receive better ratings.")
    else:
        st.write("📌 Installs alone do not guarantee higher ratings.")

    if review_corr > 0.5:
        st.write("✅ Reviews show a positive relationship with ratings.")
    else:
        st.write("📌 Reviews have a weak impact on ratings.")

st.markdown("---")

# ---------------- CONCLUSION ---------------- #
st.subheader("📌 Conclusion")

st.write("""
This dashboard helps analyze the factors influencing app success on the Google Play Store.

Key Findings:
- Higher installs do not always mean higher ratings.
- Free apps generally perform similarly to paid apps.
- Reviews are positively related to app ratings.
- Category plays an important role in app performance.
- Size and Price have only a weak relationship with ratings.
""")

st.markdown("---")

st.markdown(
    "<center><h4>📱 Google Play Store Analytics Dashboard</h4>"
    "<p>Built using Streamlit & Plotly</p></center>",
    unsafe_allow_html=True
)