# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrYR65x7ZUv-VmlPxKaQBI1Wycy8r9QS
"""

# Import libraries

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('HR_comma_sep.csv')
df.head()

df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.left.value_counts()
# 0 = Stayed
# 1 = Left

df.left.value_counts(normalize=True) * 100

df.groupby('left').mean(numeric_only=True)

pd.crosstab(df.salary, df.left)

salary_table = pd.crosstab(df['salary'], df['left'])
salary_table

salary_table.plot(kind='bar')

plt.title("Salary vs Employee Retention")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.legend(["Stayed", "Left"])
plt.show()

department_table = pd.crosstab(df.Department, df.left)

department_table

department_table.plot(kind='bar', figsize=(10,5))

plt.title("Department vs Employee Retention")
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.legend(["Stayed", "Left"])
plt.show()

salary_mapping = {
    'low': 0,
    'medium': 1,
    'high': 2
}

df['salary'] = df['salary'].map(salary_mapping)

df.head()

X = df[['satisfaction_level',
        'average_montly_hours',
        'promotion_last_5years',
        'salary',
        'time_spend_company']]

y = df['left']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=10
)

#logistic regression model
model = LogisticRegression()

#train model
model.fit(X_train, y_train)

#Predictions
prediction = model.predict(X_test)

#Accuracy
accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)