# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USXSbGggxqTokMsyYpfamZ8FmtkYDD1I
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# ---------------------------------------
# Page Configuration
# ---------------------------------------
st.set_page_config(
    page_title="Canada Per Capita Income Predictor",
    page_icon="🇨🇦",
    layout="centered"
)

st.title("🇨🇦 Canada Per Capita Income Predictor")
st.write("Predict Canada's Per Capita Income using Linear Regression.")

# ---------------------------------------
# Load Dataset
# ---------------------------------------
df = pd.read_csv("canada_per_capita_income.csv")

X = df[['year']]
y = df['per capita income (US$)']

# ---------------------------------------
# Train Model
# ---------------------------------------
model = LinearRegression()
model.fit(X, y)

# ---------------------------------------
# Dataset
# ---------------------------------------
with st.expander("📂 View Dataset"):
    st.dataframe(df)

# ---------------------------------------
# User Input
# ---------------------------------------
year = st.number_input(
    "Enter Year",
    min_value=1970,
    max_value=2100,
    value=2020
)

# ---------------------------------------
# Prediction
# ---------------------------------------
prediction = model.predict([[year]])[0]

if st.button("Predict Income"):

    st.success(
        f"Estimated Per Capita Income in {year} is **${prediction:,.2f} USD**"
    )

    # ---------------------------------------
    # Graph 1 : Scatter + Regression Line
    # ---------------------------------------
    fig, ax = plt.subplots(figsize=(8,5))

    ax.scatter(
        df["year"],
        df["per capita income (US$)"],
        color="blue",
        label="Actual Data"
    )

    ax.plot(
        df["year"],
        model.predict(X),
        color="red",
        linewidth=2,
        label="Regression Line"
    )

    ax.scatter(
        year,
        prediction,
        color="green",
        s=120,
        marker="*",
        label="Predicted Value"
    )

    ax.set_title("Canada Per Capita Income Prediction")
    ax.set_xlabel("Year")
    ax.set_ylabel("Per Capita Income (US$)")
    ax.legend()
    ax.grid(True)

    st.pyplot(fig)

# ---------------------------------------
# Income Trend
# ---------------------------------------
st.subheader("📈 Income Trend")

fig2, ax2 = plt.subplots(figsize=(8,5))

ax2.plot(
    df["year"],
    df["per capita income (US$)"],
    marker="o"
)

ax2.set_title("Canada Per Capita Income Over Years")
ax2.set_xlabel("Year")
ax2.set_ylabel("Income (US$)")
ax2.grid(True)

st.pyplot(fig2)

# ---------------------------------------
# Model Information
# ---------------------------------------
st.subheader("Model Details")

st.write(f"**Coefficient:** {model.coef_[0]:.4f}")
st.write(f"**Intercept:** {model.intercept_:.4f}")

# ---------------------------------------
# Footer
# ---------------------------------------
st.markdown("---")
st.markdown(
    "<center>Made with ❤️ using Streamlit, Scikit-Learn & Matplotlib</center>",
    unsafe_allow_html=True
)